flags: {}

resolver: lts-6.6
compiler: ghcjs-0.2.0.900006006_ghc-7.10.3

compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.900006006_ghc-7.10.3:
         url: "https://tolysz.org/ghcjs/lts-6.6-900006006.tar.gz"

allow-newer: true

packages:
- location: '.'
- '../ln-ui-core'
- '../ln-ui-reactflux'
- '../ln-sanitize'
- '../ln-validate'
- '../ln-api-ghcjs'
- '../haskell-ln-types'
- '../haskell-api-helpers-shared'
- '../haskell-api-helpers-ghcjs'
- '../haskell-either-helpers'
- '../haskell-ebyam'
- '../haskell-rehtie'
- '../haskell-ifte'
- '../haskell-web-bootstrap'
- '../ghcjs-router'
- '../ghcjs-ajax/ghcjs-ajax'
- '../react-flux-router'
- '../web-routes' ## <-- remove if PR gets accepted

extra-deps:
- ref-tf-0.4
- these-0.6.1.0
- react-flux-1.1.1
- ghcjs-dom-0.2.4.0
